#!/bin/sh

FORMAT_CMD="make check-format"
LINTER_CMD="make linter"

$($FORMAT_CMD)
FORMAT_RESULT=$?

$($LINTER_CMD)
LINTER_RESULT=$?

Result() {
    if [ $1 -eq 2 ]; then
        echo "\e[31mCommand: $2 failed\e[0m"
        exit 1
    elif [ $1 -eq 1 ]; then
        echo "\e[31m$3 status: FAILED\e[0m"
        exit 1
    else
        echo "\e[32m$3 status: PASSED\e[0m"
    fi
}

Result "$FORMAT_RESULT" "$FORMAT_CMD" "Format check"
Result "$LINTER_RESULT" "$LINTER_CMD" "Linter check"
