application:
  port: 8000
  hmac_secret: "long-and-secret-random-key-generated-to-verify-message-integrity"
database: 
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://127.0.0.1"
  sender_email: "test@gmail.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"

