name: CI

# Trigger the workflow on every push/pull-request
on: [push, pull_request]

# always display colored output used in terminal
env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains mutltiple jobs called "test", "Rustfmt", "clippy", "Code coverage"
  test:
    name: Test
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository last commit
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it: "v1" the whole repo while "v2" checkout the last commit\
        uses: actions/checkout@v2
      
      - name: Install minimal toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Run cargo-test
        uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository last commit
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          
      - name: Run cargo-fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository last commit
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      
      - name: Run cargo-clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository last commit
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests --ciserver github-ci --coveralls $COVERALLS_REPO_TOKEN'
    
      - name: Push to Coveralls
        uses: coverallsapp/github-action@2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
